# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcli < Formula
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v1.0.3/kwcli_Darwin_x86_64.tar.gz"
      sha256 "52fba009790c2247c3a7a5a1cc330ef774e832f92ad2f129bf6ea1148344c9c0"

      def install
        bin.install "kwcli"
      end
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v1.0.3/kwcli_Darwin_arm64.tar.gz"
      sha256 "6e50e59c143e1deb4d2a50bd9e0ad821e6ce2d9982ba7a539b57c9e5627587af"

      def install
        bin.install "kwcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v1.0.3/kwcli_Linux_x86_64.tar.gz"
        sha256 "41eb48702c6f858161a90b482a8281f4a37f9f2657185e2aef944e4e807f337d"

        def install
          bin.install "kwcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v1.0.3/kwcli_Linux_arm64.tar.gz"
        sha256 "3d7b2a572ce8ceaa21188679b4bfdfaa7d65cbde7d1adb5c1a9db728eda85597"

        def install
          bin.install "kwcli"
        end
      end
    end
  end
end
