# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcli < Formula
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v1.0.2/kwcli_Darwin_x86_64.tar.gz"
      sha256 "e4711122a805118b4dc5b1e7eccee8022ea02fb939cc53c26b16833c349a7156"

      def install
        bin.install "kwcli"
      end
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v1.0.2/kwcli_Darwin_arm64.tar.gz"
      sha256 "9fb7f49be8e165250a87cade442bf496459a5084fc4d2fc9dd4fb12cd13ed380"

      def install
        bin.install "kwcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v1.0.2/kwcli_Linux_x86_64.tar.gz"
        sha256 "99e809ca3e8cdbf8d8955ea9c3e98dc0fba96d8b298fcf76cfb5e65ba85da006"

        def install
          bin.install "kwcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v1.0.2/kwcli_Linux_arm64.tar.gz"
        sha256 "6d300f54af1a3b4609c2b893ecc5fe19fbea86d16ac5d7f25c1b1d45d07691c9"

        def install
          bin.install "kwcli"
        end
      end
    end
  end
end
