# This file was generated by GoReleaser. DO NOT EDIT.
cask "kwcli" do
  name "kwcli"
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.2.2-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kwcli"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_x86_64.tar.gz"
      sha256 "50a1fa33ab3bfb6fe21fde7d1daf190c582a0c593d97b836b3d5e039bc92e308"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_arm64.tar.gz"
      sha256 "569b421e715158ff1c20f033088672719f845aeed986e371ad16643ae56c2b2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_x86_64.tar.gz"
      sha256 "7c86257f2a6e5d05378e8f72afc603df068ccbd7a041361b481ef03102959c0e"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_arm64.tar.gz"
      sha256 "89a4bac06da7fca7543f5decc50217ff830504847b7ebd27a5d8adb678760a7d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kwcli"]
    end
  end

  # No zap stanza required
end
