# This file was generated by GoReleaser. DO NOT EDIT.
cask "kwcli" do
  name "kwcli"
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.4.0-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kwcli"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_x86_64.tar.gz"
      sha256 "720dba3415c6b6b3729ae7d2aec6156f10a4fd6e318f1fe3cd787455a9fefe1b"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_arm64.tar.gz"
      sha256 "a00c5c3837e31e49d4a4409ef14649a9eb697402e989216f756c8b0618358a88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_x86_64.tar.gz"
      sha256 "4e6865c536e003c1f7649a80ef70bf5c43f76bac3433bd36af2b5ffaaaa1bfdf"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_arm64.tar.gz"
      sha256 "e6f1a41cd9a41e170bbc0da230578199c10a6d6648e8ec9ab4ae24fa6c1e0ce6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kwcli"]
    end
  end

  # No zap stanza required
end
