# This file was generated by GoReleaser. DO NOT EDIT.
cask "kwcli" do
  name "kwcli"
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.3.3-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kwcli"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_x86_64.tar.gz"
      sha256 "2779383dae3c6663f87f996b4b2501d556bbee8eed5059c0cf1832cc61cadd12"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Darwin_arm64.tar.gz"
      sha256 "6dfe315eed28ee9ef2b4d957291910c0504c3ebb578dbc9f4c65cb376decbbed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_x86_64.tar.gz"
      sha256 "b2edd3704abf49da8438e2c27573fc955e14e2445f021394e9878cf35df745eb"
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v#{version}/kwcli_Linux_arm64.tar.gz"
      sha256 "0527a70326ad9597747dadf6aa30b2936ced3d01f765becf992b092c06d21b18"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kwcli"]
    end
  end

  # No zap stanza required
end
