# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcli < Formula
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.2.0-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clazic/kwcli/releases/download/v0.2.0-test/kwcli_Darwin_x86_64.tar.gz"
      sha256 "9bfb563e59cd03bf2a5bee27ea8a3da1bdbbd3c528c486bc07ccf8ea74d7f868"

      define_method(:install) do
        bin.install "kwcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clazic/kwcli/releases/download/v0.2.0-test/kwcli_Darwin_arm64.tar.gz"
      sha256 "dff10bd07d1d09ff8e2cf38cd21a4306ebb6b9c7a5cd3186357a48f9147ccf64"

      define_method(:install) do
        bin.install "kwcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clazic/kwcli/releases/download/v0.2.0-test/kwcli_Linux_x86_64.tar.gz"
      sha256 "89e3eb13f0fc5ee63812ef435c98bbc8cea4eafdcf3bc42cae62bbe7f93f8760"
      define_method(:install) do
        bin.install "kwcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clazic/kwcli/releases/download/v0.2.0-test/kwcli_Linux_arm64.tar.gz"
      sha256 "bef1611edb8f8181089daa82a65d667117d62b425bae122819e3d4adeecf9509"
      define_method(:install) do
        bin.install "kwcli"
      end
    end
  end

  test do
    system "#{bin}/kwcli --version"
  end
end
