# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcli < Formula
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.1.2-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clazic/kwcli/releases/download/v0.1.2-test/kwcli_Darwin_x86_64.tar.gz"
      sha256 "c99a5d09787ab7a4e2854ed58d2d7059d71cebcbf4dae88839a30d92af8f833f"

      define_method(:install) do
        bin.install "kwcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clazic/kwcli/releases/download/v0.1.2-test/kwcli_Darwin_arm64.tar.gz"
      sha256 "1e64f7455050b90c25436191d46d257a608f437889032f3bc828cbfcd6e3d516"

      define_method(:install) do
        bin.install "kwcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/clazic/kwcli/releases/download/v0.1.2-test/kwcli_Linux_x86_64.tar.gz"
      sha256 "ff3a851dc3a40c33cbcb053da9174c1ad5aa570a4633995f391917ba9212b58b"
      define_method(:install) do
        bin.install "kwcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clazic/kwcli/releases/download/v0.1.2-test/kwcli_Linux_arm64.tar.gz"
      sha256 "4f4aba3095a10fb67c02b4a9022292387589b69e0c76813bc99d20266da6ecb0"
      define_method(:install) do
        bin.install "kwcli"
      end
    end
  end

  test do
    system "#{bin}/kwcli --version"
  end
end
