# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwcli < Formula
  desc "Command-line tool for Korean stock market data and trading."
  homepage "https://github.com/clazic/kwcli"
  version "0.1.0-test"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/clazic/kwcli/releases/download/v0.1.0-test/kwcli_Darwin_x86_64.tar.gz"
      sha256 "5fcc93057e814998c42235fc5e9a70f026f71883514b2782d0fd994f013125fa"

      def install
        bin.install "kwcli"
      end
    end
    on_arm do
      url "https://github.com/clazic/kwcli/releases/download/v0.1.0-test/kwcli_Darwin_arm64.tar.gz"
      sha256 "7ed37f66b11b0f52c4228033ac097e85d4a5de6be9e54266efd17e7d2f6049d3"

      def install
        bin.install "kwcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v0.1.0-test/kwcli_Linux_x86_64.tar.gz"
        sha256 "d441a5c059d7ccbf58ffc130903a180ada70315902c25e687f15181c35c1987d"

        def install
          bin.install "kwcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/clazic/kwcli/releases/download/v0.1.0-test/kwcli_Linux_arm64.tar.gz"
        sha256 "2e7195cd84527985fe338ad8b5ea143a8b782377626105b44cfe844e105272d4"

        def install
          bin.install "kwcli"
        end
      end
    end
  end

  test do
    system "#{bin}/kwcli --version"
  end
end
